version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    volumes:
      - ./:/var/www/html
    ports:
      - "8080:80"
    networks:
      - payment_api

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: payment_api
      MYSQL_USER: payment_api
      MYSQL_PASSWORD: payment_api
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - payment_api

networks:
  payment_api:

volumes:
  mysql-data:
